import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { AuthProvider } from './context/authContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          {children}
          <Toaster />
        </body>
      </html>
    </AuthProvider>
  );
}
